import { TDLProduct, User } from '../types';

declare global {
    interface Window {
        Razorpay: any;
    }
}

export const loadRazorpay = (): Promise<boolean> => {
    return new Promise((resolve) => {
        if (window.Razorpay) {
            resolve(true);
            return;
        }
        const script = document.createElement('script');
        script.src = 'https://checkout.razorpay.com/v1/checkout.js';
        script.onload = () => {
            resolve(true);
        };
        script.onerror = () => {
            resolve(false);
        };
        document.body.appendChild(script);
    });
};

export const openCheckout = async (
    product: TDLProduct,
    user: User,
    onSuccess: (paymentId: string) => void,
    onFailure: (error: any) => void
) => {
    const res = await loadRazorpay();

    if (!res) {
        alert('Razorpay SDK failed to load. Are you online?');
        return;
    }

    const key = import.meta.env.VITE_RAZORPAY_KEY_ID?.trim();

    if (!key) {
        alert("Razorpay Key ID is missing! Check .env file.");
        return;
    }

    try {
        // 1. Call your Vercel API backend to create an order securely
        const response = await fetch('/api/create-order', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ amount: product.price })
        });

        if (!response.ok) {
            const errData = await response.json();
            alert(`Server Error: ${errData.error || 'Failed to create order'}`);
            onFailure(errData);
            return;
        }

        const orderData = await response.json();

        const options = {
            key: key,
            amount: product.price * 100,
            currency: "INR",
            name: "AndurilTech",
            description: `Purchase ${product.name}`,
            image: import.meta.env.VITE_LOGO_URL || "https://anduriltech.in/logo.png",
            order_id: orderData.id, // Secure order ID generated by backend
            handler: async function (response: any) {
                try {
                    // 2. We got payment payload back - we MUST verify its signature on the backend!
                    const verifyResponse = await fetch('/api/verify-payment', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            razorpay_order_id: response.razorpay_order_id,
                            razorpay_payment_id: response.razorpay_payment_id,
                            razorpay_signature: response.razorpay_signature
                        })
                    });

                    if (verifyResponse.ok) {
                        // Secure payment verified by server
                        onSuccess(response.razorpay_payment_id);
                    } else {
                        const err = await verifyResponse.json();
                        throw new Error(err.message || "Payment verification failed!");
                    }
                } catch (e: any) {
                    onFailure({ description: e.message || "Verification failed" });
                }
            },
            prefill: {
                name: user.name,
                email: user.email,
                contact: ""
            },
            notes: {
                address: "AndurilTech Corporate Office"
            },
            theme: {
                color: "#3399cc"
            },
            modal: {
                ondismiss: function () {
                    onFailure({ description: "Payment window closed by user" });
                }
            }
        };

        const paymentObject = new window.Razorpay(options);
        paymentObject.on('payment.failed', function (res: any) {
            console.error("Payment Failed Event:", res.error);
            onFailure(res.error);
        });
        paymentObject.open();

    } catch (err) {
        console.error("Error creating order/Razorpay instance:", err);
        alert("Failed to initialize secure payment session. Check console.");
    }
};
